### ISSUE TITLE
Iteration Plan - November 2018

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/vscode-js-annotations#46]
I am planning on working on switching to a monthly release schedule for this extension. Given we are late into October currently, I will start now for a November Release that will come out in early December.

The main focus is to crank out some major bugs and continue adding support across various platforms.

## Endgame

* **Last week in November**: Code freeze
* **First week in December**: Release window

### Features
- [x] Support JSX / TSX Files #37 

### Bug Fixes
- [x] Immediately invoked require() functions are improperly annotated #36 
- [x] Single Param arrow functions without parens not producing annotations #41 
- [x] The typescript `this` parameter should be ignored #50

### Documentation Work
- [x] Run just unit tests with Mocha #35 
- [x] Setup Guide in Readme #39 

---

### Deferred
- [ ] Vue Support #47 
- [ ] Annotate JS in <script> tags #48 
- [ ] Code folding causing weird duplicates #19 
- [ ] Function calls in object / array access occasionally failing #24
